=== 4Sayer/schemxml/xsd/resultados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="jornada">
        <xs:complexType>
            <xs:sequence>

            <xs:element name="partido" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>

                    <xs:element name="equipo_local" type="xs:string"/>
                    <xs:element name="equipo_visitante" type="xs:string"/>
                    <xs:element name="goles_local" type="xs:integer"/>
                    <xs:element name="goles_visitante" type="xs:integer"/>
                    <xs:element name="estadio" type="xs:string"/>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            </xs:sequence>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 4Sayer/schemxml/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<jornada fecha="2026-09-27" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/resultados.xsd">

    <partido>
        <equipo_local>Pumas</equipo_local>
        <equipo_visitante>Atletico de San Luis</equipo_visitante>
        <goles_local>2</goles_local>
        <goles_visitante>3</goles_visitante>
        <estadio>Olímpico Universitario</estadio>
    </partido>

    <partido>
        <equipo_local>Leon</equipo_local>
        <equipo_visitante>FC Juarez</equipo_visitante>
        <goles_local>2</goles_local>
        <goles_visitante>1</goles_visitante>
        <estadio>Leon</estadio>
    </partido>

    <partido>
        <equipo_local>Leon</equipo_local>
        <equipo_visitante>FC Juarez</equipo_visitante>
        <goles_local>2</goles_local>
        <goles_visitante>1</goles_visitante>
        <estadio>Leon</estadio>
    </partido>



</jornada>
